
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/modal/RegisterModal";
import LoginModal from "./components/modal/LoginModal";
import ToasterProvider from "@/providers/ToasterProvider";
import getCurrentUser from "@/hooks/getCurrentUser";
import { useUserStore } from "@/hooks/getUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ReScore",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  console.log(currentUser)


  return (
    <html lang="en">
      <body className='relative'>
        <ClientOnly>
          <Navbar currentUser={currentUser} />
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />
        </ClientOnly>

        {children}
        <Footer />
      </body>
    </html>
  );
}
