
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Loading from "./components/Loading";
import { useUserStore } from "@/hooks/getUser";
import { GridBackgroundDemo } from "@/components/ui/gridback";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='relative'>
        {/* <GridBackgroundDemo /> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
